# Generated by Django 6.0.6 on 2026-06-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('editora', models.CharField(max_length=150)),
                ('ano_publicacao', models.PositiveIntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
