# Generated by Django 6.0.6 on 2026-06-12 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_leitor_usuario_solicitacaofuncionario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacaoadmin',
            options={'ordering': ['lida', '-criada_em']},
        ),
        migrations.AlterModelOptions(
            name='solicitacaofuncionario',
            options={'ordering': ['-criada_em']},
        ),
    ]
