# Generated by Django 6.0.6 on 2026-06-12 01:59

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_alter_leitor_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoBiblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo_emprestimo_dias', models.PositiveIntegerField(default=15, verbose_name='Prazo do empréstimo em dias')),
                ('prazo_renovacao_dias', models.PositiveIntegerField(default=15, verbose_name='Prazo adicional da renovação')),
                ('prazo_retirada_reserva_horas', models.PositiveIntegerField(default=24, verbose_name='Prazo para retirada da reserva')),
                ('limite_emprestimos_leitor', models.PositiveIntegerField(default=2)),
                ('limite_emprestimos_funcionario', models.PositiveIntegerField(default=3)),
                ('valor_multa_diaria', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, verbose_name='Valor da multa por dia')),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da biblioteca',
                'verbose_name_plural': 'Configurações da biblioteca',
            },
        ),
        migrations.AlterModelOptions(
            name='notificacaoadmin',
            options={'ordering': ['lida', '-criada_em'], 'verbose_name': 'Notificação administrativa', 'verbose_name_plural': 'Notificações administrativas'},
        ),
        migrations.AlterModelOptions(
            name='solicitacaofuncionario',
            options={'ordering': ['-criada_em'], 'verbose_name': 'Solicitação de funcionário', 'verbose_name_plural': 'Solicitações de funcionários'},
        ),
        migrations.AlterField(
            model_name='obra',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade de exemplares'),
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número da cópia')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('RESERVADO', 'Reservado'), ('EMPRESTADO', 'Emprestado'), ('MANUTENCAO', 'Em manutenção'), ('EXTRAVIADO', 'Extraviado'), ('BAIXADO', 'Baixado')], default='DISPONIVEL', max_length=20)),
                ('somente_consulta', models.BooleanField(default=False, editable=False, verbose_name='Somente consulta local')),
                ('motivo_baixa', models.TextField(blank=True)),
                ('baixado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplares', to='biblioteca.obra')),
            ],
            options={
                'verbose_name': 'Exemplar',
                'verbose_name_plural': 'Exemplares',
                'ordering': ['obra__titulo', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_prevista_devolucao', models.DateTimeField(blank=True, null=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('DEVOLVIDO', 'Devolvido'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=15)),
                ('quantidade_renovacoes', models.PositiveIntegerField(default=0)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_registrados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to=settings.AUTH_USER_MODEL)),
                ('exemplar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='biblioteca.exemplar')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-data_emprestimo'],
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_atraso', models.PositiveIntegerField(default=0)),
                ('valor_diario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=15)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('paga_em', models.DateTimeField(blank=True, null=True)),
                ('emprestimo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multa', to='biblioteca.emprestimo')),
                ('registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CADASTRO', 'Cadastro'), ('ALTERACAO', 'Alteração'), ('EXCLUSAO', 'Exclusão'), ('LOGIN', 'Entrada no sistema'), ('LOGOUT', 'Saída do sistema'), ('APROVACAO', 'Aprovação'), ('RECUSA', 'Recusa'), ('RESERVA', 'Reserva'), ('EMPRESTIMO', 'Empréstimo'), ('RENOVACAO', 'Renovação'), ('DEVOLUCAO', 'Devolução'), ('MULTA', 'Multa'), ('BAIXA', 'Baixa de exemplar')], max_length=20)),
                ('entidade', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(blank=True, max_length=50)),
                ('descricao', models.TextField()),
                ('dados_anteriores', models.JSONField(blank=True, null=True)),
                ('dados_novos', models.JSONField(blank=True, null=True)),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_auditadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Registros de auditoria',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Renovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_anterior', models.DateTimeField()),
                ('nova_data', models.DateTimeField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovacoes', to='biblioteca.emprestimo')),
                ('solicitada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovacoes_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Renovação',
                'verbose_name_plural': 'Renovações',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FILA', 'Na fila de espera'), ('AGUARDANDO_RETIRADA', 'Aguardando retirada'), ('RETIRADA', 'Retirada'), ('EXPIRADA', 'Expirada'), ('CANCELADA', 'Cancelada')], default='FILA', max_length=25)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('disponivel_em', models.DateTimeField(blank=True, null=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('exemplar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='biblioteca.exemplar')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='biblioteca.obra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['criada_em'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NOVA_RESERVA', 'Nova reserva de leitor'), ('LIVRO_DISPONIVEL', 'Livro disponível para retirada'), ('RESERVA_EXPIRADA', 'Reserva expirada')], default='NOVA_RESERVA', max_length=25)),
                ('titulo', models.CharField(max_length=150)),
                ('mensagem', models.TextField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True)),
                ('lida_por', models.ManyToManyField(blank=True, related_name='notificacoes_funcionario_lidas', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_funcionarios', to='biblioteca.reserva')),
            ],
            options={
                'verbose_name': 'Notificação de funcionário',
                'verbose_name_plural': 'Notificações de funcionários',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='reserva',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimo', to='biblioteca.reserva'),
        ),
        migrations.AddConstraint(
            model_name='exemplar',
            constraint=models.UniqueConstraint(fields=('obra', 'numero'), name='exemplar_unico_por_obra_numero'),
        ),
        migrations.AddConstraint(
            model_name='exemplar',
            constraint=models.CheckConstraint(condition=models.Q(('numero__gte', 1)), name='numero_exemplar_maior_ou_igual_um'),
        ),
        migrations.AddConstraint(
            model_name='exemplar',
            constraint=models.CheckConstraint(condition=models.Q(('numero', 1), ('status__in', ['RESERVADO', 'EMPRESTADO']), _negated=True), name='copia_um_nao_pode_circular'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['FILA', 'AGUARDANDO_RETIRADA'])), fields=('usuario', 'obra'), name='reserva_ativa_unica_usuario_obra'),
        ),
        migrations.AddConstraint(
            model_name='emprestimo',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ATIVO')), fields=('exemplar',), name='um_emprestimo_ativo_por_exemplar'),
        ),
    ]
