# Generated by Django 6.0.6 on 2026-06-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_configuracaobiblioteca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
